window.PROGRAMA_PUNTEL = {
  meta: {
    title: "Visita Institucional — Alte Esq Leonardo Puntel",
    subtitle: "Agenda na área do Comando do 3º Distrito Naval",
    timezone: "America/Fortaleza",
    timezoneLabel: "BRT · UTC−3",
    organization: "Comando do 3º Distrito Naval",
    authority: "Almirante de Esquadra Leonardo Puntel",
    role: "Ministro do Superior Tribunal Militar",
    formerRole: "Ex-Comandante de Operações Navais da Marinha do Brasil",
    officialBioUrl: "https://dspace.stm.jus.br/handle/123456789/164437",
    lastUpdated: "2026-09-11"
  },

  events: [
    {
      id: "joao-pessoa",
      city: "João Pessoa/PB",
      shortCity: "João Pessoa",
      title: "VI FÓRUM OEA — Boas Práticas do Sistema de Justiça Brasileiro",
      start: "2026-09-24T00:00:00-03:00",
      end: "2026-09-26T23:59:59-03:00",
      dateLabel: "24 a 26SET2026",
      venue: "Auditório da Procuradoria-Geral de Justiça",
      programStatus: "Programação detalhada indicada como anexa no documento-base. Hospedagem registrada: HT-JP.",
      participants: ["AE Puntel e esposa", "Min Péricles e esposa"],
      lodging: "HT-JP",
      flights: [
        { date: "2026-09-24", passenger: "AE Puntel", depart: "08:40", arrive: "11:25", from: "Brasília (BSB)", to: "João Pessoa (JPA)" },
        { date: "2026-09-24", passenger: "D. Mônica", depart: "09:20", arrive: "12:10", from: "Rio de Janeiro (GIG)", to: "João Pessoa (JPA)" },
        { date: "2026-09-27", passenger: "D. Mônica", depart: "11:55", arrive: "14:40", from: "João Pessoa (JPA)", to: "Brasília (BSB)" },
        { date: "2026-09-27", passenger: "AE Puntel", depart: "11:55", arrive: "14:40", from: "João Pessoa (JPA)", to: "Brasília (BSB)" }
      ]
    },
    {
      id: "fortaleza",
      city: "Fortaleza/CE",
      shortCity: "Fortaleza",
      title: "Cerimônia de entrega da OMJM e palestra na EAMCE",
      start: "2026-10-14T00:00:00-03:00",
      end: "2026-10-16T23:59:59-03:00",
      dateLabel: "14 a 16OUT2026",
      venue: "10ª Circunscrição Judiciária Militar (10ª CJM) e EAMCE",
      programStatus: "Programação a cargo do Com3ºDN e da 10ª CJM. Auditório da EAMCE a definir. Hospedagem registrada: HT-EAMCE.",
      participants: ["AE Puntel"],
      lodging: "HT-EAMCE",
      flights: [
        { date: "2026-10-14", passenger: "AE Puntel", depart: "08:25", arrive: "11:35", from: "Rio de Janeiro (GIG)", to: "Fortaleza (FOR)" },
        { date: "2026-10-16", passenger: "AE Puntel", depart: "18:20", arrive: "20:05", from: "Fortaleza (FOR)", to: "São Paulo (GRU)" }
      ]
    },
    {
      id: "recife",
      city: "Recife/PE",
      shortCity: "Recife",
      title: "Congresso Jurídico de Direito Militar — Congresso Anual da ENAJUM",
      subtitle: "Geopolítica, Soberania e os Novos Desafios do Poder Judiciário",
      start: "2026-10-27T00:00:00-03:00",
      end: "2026-10-31T23:59:59-03:00",
      dateLabel: "27 a 31OUT2026",
      venue: "Mar Hotel Conventions",
      programStatus: "Programação detalhada aguardando. Hospedagem registrada: Mar Hotel Conventions.",
      participants: ["AE Puntel e esposa"],
      lodging: "Mar Hotel Conventions",
      flights: [
        { date: "2026-10-27", passenger: "D. Mônica", depart: "13:15", arrive: "16:05", from: "Rio de Janeiro (GIG)", to: "Recife (REC)" },
        { date: "2026-10-27", passenger: "AE Puntel", depart: "13:15", arrive: "16:05", from: "Rio de Janeiro (GIG)", to: "Recife (REC)" },
        { date: "2026-10-31", passenger: "D. Mônica", depart: "10:25", arrive: "13:20", from: "Recife (REC)", to: "Rio de Janeiro (GIG)" },
        { date: "2026-10-31", passenger: "AE Puntel", depart: "10:25", arrive: "13:20", from: "Recife (REC)", to: "Rio de Janeiro (GIG)" }
      ]
    }
  ],

  biography: {
    birth: "27 de novembro de 1958, Belo Horizonte/MG",
    parents: "Luiz Gonzaga Puntel e Lya Apparecida Puntel",
    family: "Casado com a Sra. Mônica Pitombeira Fernandes Puntel; dois filhos: Leonardo Fernandes Puntel e Luiz Fernandes Puntel",
    stmAppointment: "Nomeado Ministro do Superior Tribunal Militar por Decreto de 29 de setembro de 2020; tomou posse em 2 de outubro de 2020.",
    ranks: [
      ["Aluno do Colégio Naval", "01MAR1973"],
      ["Aspirante", "03FEV1975"],
      ["Guarda-Marinha", "13DEZ1979"],
      ["Segundo-Tenente", "31AGO1980"],
      ["Primeiro-Tenente", "31AGO1982"],
      ["Capitão-Tenente", "31AGO1985"],
      ["Capitão de Corveta", "31AGO1991"],
      ["Capitão de Fragata", "30ABR1997"],
      ["Capitão de Mar e Guerra", "31AGO2002"],
      ["Contra-Almirante", "31JUL2009"],
      ["Vice-Almirante", "31MAR2013"],
      ["Almirante de Esquadra", "25NOV2016"]
    ],
    commissions: [
      "Navio Socorro de Submarinos Gastão Moutinho — Encarregado de Divisão",
      "Contratorpedeiro Marcílio Dias — Encarregado de Divisão",
      "Fragata Niterói — Encarregado de Divisão",
      "Aviso de Instrução Aspirante Nascimento — Imediato",
      "Grupo de Recebimento de Navio nos EUA — Contratorpedeiro Pará — Oficial de Ligação",
      "Comando de Operações Navais — Assistente",
      "Comando da Força de Apoio — Assistente",
      "Escola de Guerra Naval — Instrutor",
      "Rebocador de Alto-Mar Almirante Guilhem — Comandante",
      "Gabinete do Ministro da Marinha — Assessor",
      "Comando em Chefe da Esquadra do Atlântico da Marinha dos Estados Unidos da América — Oficial de Ligação",
      "Diretoria-Geral do Material da Marinha — Oficial de Gabinete",
      "Comando de Operações Navais — Encarregado de Divisão",
      "Comando do 5º Distrito Naval — Chefe do Estado-Maior",
      "Escola Naval",
      "Navio Veleiro Cisne Branco — Comandante",
      "Diretoria-Geral do Pessoal da Marinha — Chefe de Gabinete",
      "Comando do 1º Distrito Naval — Chefe do Estado-Maior",
      "Escola Naval — Comandante",
      "Diretoria de Ensino da Marinha — Diretor",
      "Comando do 5º Distrito Naval — Comandante",
      "Comando do 1º Distrito Naval — Comandante",
      "Estado-Maior Conjunto das Forças Armadas — Chefe de Logística e Mobilização e Chefe de Assuntos Estratégicos",
      "Diretoria-Geral de Navegação — Diretor-Geral",
      "Comando de Operações Navais — Comandante"
    ],
    courses: [
      "Colégio Naval",
      "Escola Naval",
      "Curso de Combate a Incêndio — Centro de Adestramento Almirante Marques de Leão",
      "Curso de Controle de Avarias — Centro de Adestramento Almirante Marques de Leão",
      "Curso de Oficial de Serviço no Centro de Informação de Combate — Contratorpedeiro Marcílio Dias",
      "Curso de Aperfeiçoamento de Armamento para Oficiais — Centro de Instrução Almirante Wandenkolk",
      "Curso de QF-9 (MHLS) — Fragata Niterói",
      "Curso de INSIAC-OF — Fragata Niterói",
      "Curso de Direção de Tiro de Armas Acima d’Água — Centro de Adestramento Almirante Marques de Leão",
      "Curso de COFON — Centro de Adestramento Almirante Marques de Leão",
      "Curso de Gestão por Excelência para Oficiais — Centro de Adestramento Almirante Marques de Leão",
      "Curso Expedito de Equipe de Manobra de Helicóptero e Crache — Centro de Instrução e Adestramento Aeronaval Almirante José Maria do Amaral Oliveira",
      "Curso Expedito de Sistema de Mísseis Seacat (Fragatas) — Centro de Instrução Almirante Wandenkolk",
      "Curso Expedito de OSAVN — Centro de Instrução e Adestramento Aeronaval Almirante José Maria do Amaral Oliveira",
      "Curso A-113-0097 — MK 56 GFCS Maintenance — U.S. Coast Guard",
      "Curso Básico — Escola de Guerra Naval",
      "Curso de Comando e Estado-Maior — Escola de Guerra Naval",
      "Curso Expedito OF-Salvo — Centro de Adestramento Almirante Marques de Leão",
      "Curso Superior de Guerra Naval — Escola de Guerra Naval",
      "MBA em Gestão Internacional — UFRJ/COPPEAD",
      "Curso de Política e Estratégia Marítimas — Escola de Guerra Naval"
    ],
    decorations: [
      "Ordem do Mérito da Defesa — Grã-Cruz",
      "Ordem do Mérito Naval — Grã-Cruz",
      "Ordem do Mérito Militar — Grande-Oficial",
      "Ordem do Mérito Aeronáutico — Grande-Oficial",
      "Ordem de Rio Branco — Grã-Cruz",
      "Ordem do Mérito Judiciário Militar — Grã-Cruz",
      "Medalha da Vitória",
      "Medalha Mérito Desportivo Militar",
      "Medalha Mérito Estado-Maior Conjunto das Forças Armadas",
      "Medalha Militar de Ouro — passador de Platina",
      "Medalha Mérito Tamandaré",
      "Medalha do Mérito Marinheiro — quatro âncoras",
      "Medalha do Pacificador",
      "Medalha Mérito Santos Dumont",
      "Medalha-Prêmio Escola de Guerra Naval",
      "US Navy Commendation Medal",
      "Medalha da Defesa Nacional Francesa — Prata",
      "Medalha Pro Memoria — Polônia",
      "Medalha Pro Patria — Polônia",
      "Ordem do Mérito do Conselho Internacional do Esporte Militar (CISM)",
      "Medalha do Mérito Marechal Cordeiro de Faria"
    ]
  }
};
